# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
# add to alerting_rules start
  - /etc/prometheus/alerting_rules/blackbox.yml
  - /etc/prometheus/alerting_rules/node_monitoring.yml
  - /etc/prometheus/alerting_rules/test_httpserver_log.yml
  - /etc/prometheus/alerting_rules/test_httpserver_request.yml
# add to alerting_rules end
# add to recording_rules start
  - /etc/prometheus/recording_rules/node.yml
  - /etc/prometheus/recording_rules/test_httpserver.yml
# add to recording_rules start

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

# add to scrape_configs start
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "blackbox_exporter_tcp"
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - localhost:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: "blackbox_exporter_http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - localhost:8081/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: "grok_exporter"
    static_configs:
      - targets: ["localhost:9144"]
    metric_relabel_configs:  
      - source_labels: [__name__]
        regex: ^go_.*
        action: drop
  - job_name: "test_httpserver"
    static_configs:
      - targets: ["localhost:8081"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: ^a_.*
        action: keep
# add to scrape_configs end
